=== Glucks-GmbH/BASE/libs/base.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="BASE">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="virtual_hosts">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="host" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="domain" type="xsd:string">
                                        </xsd:element>
                                        <xsd:element name="localCode" type="xsd:string">
                                        </xsd:element>
                                        <xsd:element name="allowedLocalCodes" minOccurs="0">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="localCode" maxOccurs="unbounded"
                                                                 type="xsd:string">
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="templates">
                    <xsd:complexType>
                        <xsd:sequence>
                        </xsd:sequence>
                        <xsd:attribute name="engine" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Glucks-GmbH/BASE/phpunit/dataProvider/ConfigTest/missingTemplateEngine/config/base.xml
<?xml version="1.0" encoding="UTF-8" ?>
<BASE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../libs/base.xsd">
    <virtual_hosts>
        <host>
            <domain>localhost:51111</domain>
            <localCode>de-de</localCode>
            <allowedLocalCodes>
                <localCode>en-de</localCode>
                <localCode>fr-de</localCode>
            </allowedLocalCodes>
        </host>
        <host>
            <domain>local.de</domain>
            <localCode>de-de</localCode>
            <allowedLocalCodes>
                <localCode>fr-de</localCode>
            </allowedLocalCodes>
        </host>
    </virtual_hosts>
</BASE>
