=== Glucks-GmbH/BASE/libs/routes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="routes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="route" minOccurs="0" maxOccurs="unbounded">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="route">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="uri" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="code" type="xsd:string" use="required"/>
                        <xsd:attribute name="value" type="xsd:string" use="required"/>
                        <xsd:attribute name="regExp" type="xsd:string" fixed="true"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="subroutes" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element ref="route" minOccurs="0" maxOccurs="unbounded">
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="controller" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Glucks-GmbH/BASE/config/routes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../libs/routes.xsd">
    <route controller="/Website::homepage">
        <uri code="de-de" value="/"></uri>
        <uri code="fr-de" value="/"></uri>
    </route>
    <route controller="/About::overview">
        <uri code="de-de" value="about/"></uri>
        <subroutes>
            <route controller="/About::history">
                <uri code="de-de" value="history"></uri>
            </route>
        </subroutes>
    </route>
    <route controller="/Stores::overview">
        <uri code="*" value="/stores/"></uri>
        <subroutes>
            <route controller="/Stores::details">
                <uri code="*" value="([a-z]{1,})" regExp="true"></uri>
            </route>
        </subroutes>
    </route>
</routes>
